// Compiles a dart2wasm-generated main module from `source` which can then
// instantiatable via the `instantiate` method.
//
// `source` needs to be a `Response` object (or promise thereof) e.g. created
// via the `fetch()` JS API.
export async function compileStreaming(source) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(
      await WebAssembly.compileStreaming(source, builtins), builtins);
}

// Compiles a dart2wasm-generated wasm modules from `bytes` which is then
// instantiatable via the `instantiate` method.
export async function compile(bytes) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(await WebAssembly.compile(bytes, builtins), builtins);
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export async function instantiate(modulePromise, importObjectPromise) {
  var moduleOrCompiledApp = await modulePromise;
  if (!(moduleOrCompiledApp instanceof CompiledApp)) {
    moduleOrCompiledApp = new CompiledApp(moduleOrCompiledApp);
  }
  const instantiatedApp = await moduleOrCompiledApp.instantiate(await importObjectPromise);
  return instantiatedApp.instantiatedModule;
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export const invoke = (moduleInstance, ...args) => {
  moduleInstance.exports.$invokeMain(args);
}

class CompiledApp {
  constructor(module, builtins) {
    this.module = module;
    this.builtins = builtins;
  }

  // The second argument is an options object containing:
  // `loadDeferredModule` is a JS function that takes a module name matching a
  //   wasm file produced by the dart2wasm compiler and returns the bytes to
  //   load the module. These bytes can be in either a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  // `loadDynamicModule` is a JS function that takes two string names matching,
  //   in order, a wasm file produced by the dart2wasm compiler during dynamic
  //   module compilation and a corresponding js file produced by the same
  //   compilation. It should return a JS Array containing 2 elements. The first
  //   should be the bytes for the wasm module in a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`. The second
  //   should be the result of using the JS 'import' API on the js file path.
  // `loadDeferredId` is a JS function that takes a string corresponding to a load
  //   ID generated by the compiler when 'load-ids' option is passed. Each load
  //   ID maps to one or more WASM modules produced by the compiler. This
  //   function should return an array of byte arrays corresponding to all the
  //   modules specified by that load ID. The arrays should be in a format
  //   supported by `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  async instantiate(additionalImports,
      {loadDeferredModule, loadDynamicModule, loadDeferredId} = {}) {
    let dartInstance;

    // Prints to the console
    function printToConsole(value) {
      if (typeof dartPrint == "function") {
        dartPrint(value);
        return;
      }
      if (typeof console == "object" && typeof console.log != "undefined") {
        console.log(value);
        return;
      }
      if (typeof print == "function") {
        print(value);
        return;
      }

      throw "Unable to print message: " + value;
    }

    // A special symbol attached to functions that wrap Dart functions.
    const jsWrappedDartFunctionSymbol = Symbol("JSWrappedDartFunction");

    function finalizeWrapper(dartFunction, wrapped) {
      wrapped.dartFunction = dartFunction;
      wrapped[jsWrappedDartFunctionSymbol] = true;
      return wrapped;
    }

    // Imports
    const dart2wasm = {
            _9: () => new Error().stack,
      _18: (exn) => exn.toString(),
      _19: (exn) => {
        if (exn instanceof Error) {
          return exn.stack;
        } else {
          return null;
        }
      },
      _20: (exn) => {
        let stackString = exn.toString();
        let frames = stackString.split('\n');
        let drop = 2;
        if (frames[0].startsWith('Error')) {
            drop += 1;
        }
        return frames.slice(drop).join('\n');
      },
      _33: s => JSON.stringify(s),
      _34: s => printToConsole(s),
      _35: o => {
        if (o === null || o === undefined) return 0;
        if (typeof(o) === 'string') return 1;
        return 2;
      },
      _44: Function.prototype.call.bind(String.prototype.indexOf),
      _45: (s, p, i) => s.lastIndexOf(p, i),
      _83: x0 => new Array(x0),
      _88: (x0,x1,x2) => { x0[x1] = x2 },
      _92: (x0,x1,x2) => new DataView(x0,x1,x2),
      _94: x0 => new Int8Array(x0),
      _95: (x0,x1,x2) => new Uint8Array(x0,x1,x2),
      _96: x0 => new Uint8Array(x0),
      _98: x0 => new Uint8ClampedArray(x0),
      _100: x0 => new Int16Array(x0),
      _102: x0 => new Uint16Array(x0),
      _104: x0 => new Int32Array(x0),
      _106: x0 => new Uint32Array(x0),
      _108: x0 => new Float32Array(x0),
      _110: x0 => new Float64Array(x0),
      _135: x0 => x0.random(),
      _138: () => globalThis.Math,
      _155: (c) =>
      queueMicrotask(() => dartInstance.exports.$invokeCallback(c)),
      _162: o => o === undefined,
      _164: o => typeof o === 'function' && o[jsWrappedDartFunctionSymbol] === true,
      _168: (l, r) => l === r,
      _169: o => o,
      _170: o => {
        if (o === undefined || o === null) return 0;
        if (typeof o === 'number') return 1;
        return 2;
      },
      _171: o => o,
      _172: o => {
        if (o === undefined || o === null) return 0;
        if (typeof o === 'boolean') return 1;
        return 2;
      },
      _173: o => o,
      _174: b => !!b,
      _175: o => o.length,
      _177: (o, i) => o[i],
      _178: f => f.dartFunction,
      _185: (o, p) => o[p],
      _189: o => String(o),
      _190: (p, s, f) => p.then(s, (e) => f(e, e === undefined)),
      _191: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._191(f,arguments.length,x0) }),
      _192: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._192(f,arguments.length,x0,x1) }),
      _193: o => {
        if (o === undefined) return 1;
        var type = typeof o;
        if (type === 'boolean') return 2;
        if (type === 'number') return 3;
        if (type === 'string') return 4;
        if (o instanceof Array) return 5;
        if (ArrayBuffer.isView(o)) {
          if (o instanceof Int8Array) return 6;
          if (o instanceof Uint8Array) return 7;
          if (o instanceof Uint8ClampedArray) return 8;
          if (o instanceof Int16Array) return 9;
          if (o instanceof Uint16Array) return 10;
          if (o instanceof Int32Array) return 11;
          if (o instanceof Uint32Array) return 12;
          if (o instanceof Float32Array) return 13;
          if (o instanceof Float64Array) return 14;
          if (o instanceof DataView) return 15;
        }
        if (o instanceof ArrayBuffer) return 16;
        // Feature check for `SharedArrayBuffer` before doing a type-check.
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
            return 17;
        }
        if (o instanceof Promise) return 18;
        return 19;
      },
      _208: x0 => new ArrayBuffer(x0),
      _229: (x0,x1) => x0.createElement(x1),
      _231: (x0,x1) => x0.querySelector(x1),
      _241: (x0,x1) => x0.replaceChildren(x1),
      _242: x0 => x0.toolVersion,
      _243: x0 => x0.gitInfo,
      _263: o => {
        if (o === null || o === undefined) return 0;
        if (o instanceof Uint8Array) return 1;
        return 2;
      },
      _264: (o, start, length) => new Uint8Array(o.buffer, o.byteOffset + start, length),
      _265: o => {
        if (o === null || o === undefined) return 0;
        if (o instanceof Int8Array) return 1;
        return 2;
      },
      _266: (o, start, length) => new Int8Array(o.buffer, o.byteOffset + start, length),
      _267: o => o instanceof Uint8ClampedArray,
      _268: (o, start, length) => new Uint8ClampedArray(o.buffer, o.byteOffset + start, length),
      _269: o => o instanceof Uint16Array,
      _270: (o, start, length) => new Uint16Array(o.buffer, o.byteOffset + start, length),
      _271: o => o instanceof Int16Array,
      _272: (o, start, length) => new Int16Array(o.buffer, o.byteOffset + start, length),
      _273: o => {
        if (o === null || o === undefined) return 0;
        if (o instanceof Uint32Array) return 1;
        return 2;
      },
      _274: (o, start, length) => new Uint32Array(o.buffer, o.byteOffset + start, length),
      _275: o => {
        if (o === null || o === undefined) return 0;
        if (o instanceof Int32Array) return 1;
        return 2;
      },
      _276: (o, start, length) => new Int32Array(o.buffer, o.byteOffset + start, length),
      _279: o => {
        if (o === null || o === undefined) return 0;
        if (o instanceof Float32Array) return 1;
        return 2;
      },
      _280: (o, start, length) => new Float32Array(o.buffer, o.byteOffset + start, length),
      _281: o => {
        if (o === null || o === undefined) return 0;
        if (o instanceof Float64Array) return 1;
        return 2;
      },
      _282: (o, start, length) => new Float64Array(o.buffer, o.byteOffset + start, length),
      _283: (t, s) => t.set(s),
      _285: (o) => new DataView(o.buffer, o.byteOffset, o.byteLength),
      _287: o => o.buffer,
      _288: o => o.byteOffset,
      _289: Function.prototype.call.bind(Object.getOwnPropertyDescriptor(DataView.prototype, 'byteLength').get),
      _290: (b, o) => new DataView(b, o),
      _291: (b, o, l) => new DataView(b, o, l),
      _292: Function.prototype.call.bind(DataView.prototype.getUint8),
      _293: Function.prototype.call.bind(DataView.prototype.setUint8),
      _294: Function.prototype.call.bind(DataView.prototype.getInt8),
      _295: Function.prototype.call.bind(DataView.prototype.setInt8),
      _296: Function.prototype.call.bind(DataView.prototype.getUint16),
      _297: Function.prototype.call.bind(DataView.prototype.setUint16),
      _298: Function.prototype.call.bind(DataView.prototype.getInt16),
      _299: Function.prototype.call.bind(DataView.prototype.setInt16),
      _300: Function.prototype.call.bind(DataView.prototype.getUint32),
      _301: Function.prototype.call.bind(DataView.prototype.setUint32),
      _302: Function.prototype.call.bind(DataView.prototype.getInt32),
      _303: Function.prototype.call.bind(DataView.prototype.setInt32),
      _308: Function.prototype.call.bind(DataView.prototype.getFloat32),
      _309: Function.prototype.call.bind(DataView.prototype.setFloat32),
      _310: Function.prototype.call.bind(DataView.prototype.getFloat64),
      _311: Function.prototype.call.bind(DataView.prototype.setFloat64),
      _312: Function.prototype.call.bind(Number.prototype.toString),
      _313: Function.prototype.call.bind(BigInt.prototype.toString),
      _314: Function.prototype.call.bind(Number.prototype.toString),
      _827: (x0,x1) => { x0.text = x1 },
      _841: (x0,x1) => { x0.href = x1 },
      _2163: () => globalThis.window,
      _2169: (x0,x1) => x0[x1],
      _4841: (x0,x1) => { x0.textContent = x1 },
      _4845: () => globalThis.document,

    };

    const baseImports = {
      dart2wasm: dart2wasm,
      Math: Math,
      Date: Date,
      Object: Object,
      Array: Array,
      Reflect: Reflect,
      WebAssembly: {
        JSTag: WebAssembly.JSTag,
      },
      "": new Proxy({}, { get(_, prop) { return prop; } }),

    };

    const jsStringPolyfill = {
      "charCodeAt": (s, i) => s.charCodeAt(i),
      "compare": (s1, s2) => {
        if (s1 < s2) return -1;
        if (s1 > s2) return 1;
        return 0;
      },
      "concat": (s1, s2) => s1 + s2,
      "equals": (s1, s2) => s1 === s2,
      "fromCharCode": (i) => String.fromCharCode(i),
      "length": (s) => s.length,
      "substring": (s, a, b) => s.substring(a, b),
      "fromCharCodeArray": (a, start, end) => {
        if (end <= start) return '';

        const read = dartInstance.exports.$wasmI16ArrayGet;
        let result = '';
        let index = start;
        const chunkLength = Math.min(end - index, 500);
        let array = new Array(chunkLength);
        while (index < end) {
          const newChunkLength = Math.min(end - index, 500);
          for (let i = 0; i < newChunkLength; i++) {
            array[i] = read(a, index++);
          }
          if (newChunkLength < chunkLength) {
            array = array.slice(0, newChunkLength);
          }
          result += String.fromCharCode(...array);
        }
        return result;
      },
      "intoCharCodeArray": (s, a, start) => {
        if (s === '') return 0;

        const write = dartInstance.exports.$wasmI16ArraySet;
        for (var i = 0; i < s.length; ++i) {
          write(a, start++, s.charCodeAt(i));
        }
        return s.length;
      },
      "test": (s) => typeof s == "string",
    };


    

    dartInstance = await WebAssembly.instantiate(this.module, {
      ...baseImports,
      ...additionalImports,
      
      "wasm:js-string": jsStringPolyfill,
    });
    dartInstance.exports.$setThisModule(dartInstance);

    return new InstantiatedApp(this, dartInstance);
  }
}

class InstantiatedApp {
  constructor(compiledApp, instantiatedModule) {
    this.compiledApp = compiledApp;
    this.instantiatedModule = instantiatedModule;
  }

  // Call the main function with the given arguments.
  invokeMain(...args) {
    this.instantiatedModule.exports.$invokeMain(args);
  }
}
