// Compiles a dart2wasm-generated main module from `source` which can then
// instantiatable via the `instantiate` method.
//
// `source` needs to be a `Response` object (or promise thereof) e.g. created
// via the `fetch()` JS API.
export async function compileStreaming(source) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(
      await WebAssembly.compileStreaming(source, builtins), builtins);
}

// Compiles a dart2wasm-generated wasm modules from `bytes` which is then
// instantiatable via the `instantiate` method.
export async function compile(bytes) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(await WebAssembly.compile(bytes, builtins), builtins);
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export async function instantiate(modulePromise, importObjectPromise) {
  var moduleOrCompiledApp = await modulePromise;
  if (!(moduleOrCompiledApp instanceof CompiledApp)) {
    moduleOrCompiledApp = new CompiledApp(moduleOrCompiledApp);
  }
  const instantiatedApp = await moduleOrCompiledApp.instantiate(await importObjectPromise);
  return instantiatedApp.instantiatedModule;
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export const invoke = (moduleInstance, ...args) => {
  moduleInstance.exports.$invokeMain(args);
}

class CompiledApp {
  constructor(module, builtins) {
    this.module = module;
    this.builtins = builtins;
  }

  // The second argument is an options object containing:
  // `loadDeferredModule` is a JS function that takes a module name matching a
  //   wasm file produced by the dart2wasm compiler and returns the bytes to
  //   load the module. These bytes can be in either a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  // `loadDynamicModule` is a JS function that takes two string names matching,
  //   in order, a wasm file produced by the dart2wasm compiler during dynamic
  //   module compilation and a corresponding js file produced by the same
  //   compilation. It should return a JS Array containing 2 elements. The first
  //   should be the bytes for the wasm module in a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`. The second
  //   should be the result of using the JS 'import' API on the js file path.
  // `loadDeferredId` is a JS function that takes a string corresponding to a load
  //   ID generated by the compiler when 'load-ids' option is passed. Each load
  //   ID maps to one or more WASM modules produced by the compiler. This
  //   function should return an array of byte arrays corresponding to all the
  //   modules specified by that load ID. The arrays should be in a format
  //   supported by `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  async instantiate(additionalImports,
      {loadDeferredModule, loadDynamicModule, loadDeferredId} = {}) {
    let dartInstance;

    // Prints to the console
    function printToConsole(value) {
      if (typeof dartPrint == "function") {
        dartPrint(value);
        return;
      }
      if (typeof console == "object" && typeof console.log != "undefined") {
        console.log(value);
        return;
      }
      if (typeof print == "function") {
        print(value);
        return;
      }

      throw "Unable to print message: " + value;
    }

    // A special symbol attached to functions that wrap Dart functions.
    const jsWrappedDartFunctionSymbol = Symbol("JSWrappedDartFunction");

    function finalizeWrapper(dartFunction, wrapped) {
      wrapped.dartFunction = dartFunction;
      wrapped[jsWrappedDartFunctionSymbol] = true;
      return wrapped;
    }

    // Imports
    const dart2wasm = {
            _9: () => {
        let stackString = new Error().stack.toString();
        let frames = stackString.split('\n');
        let drop = 2;
        if (frames[0] === 'Error') {
            drop += 1;
        }
        return frames.slice(drop).join('\n');
      },
      _30: s => JSON.stringify(s),
      _31: s => printToConsole(s),
      _40: Function.prototype.call.bind(String.prototype.indexOf),
      _41: (s, p, i) => s.lastIndexOf(p, i),
      _79: x0 => new Array(x0),
      _84: (x0,x1,x2) => { x0[x1] = x2 },
      _88: (x0,x1,x2) => new DataView(x0,x1,x2),
      _90: x0 => new Int8Array(x0),
      _91: (x0,x1,x2) => new Uint8Array(x0,x1,x2),
      _92: x0 => new Uint8Array(x0),
      _94: x0 => new Uint8ClampedArray(x0),
      _96: x0 => new Int16Array(x0),
      _98: x0 => new Uint16Array(x0),
      _100: x0 => new Int32Array(x0),
      _102: x0 => new Uint32Array(x0),
      _104: x0 => new Float32Array(x0),
      _106: x0 => new Float64Array(x0),
      _113: x0 => x0.random(),
      _116: () => globalThis.Math,
      _133: (c) =>
      queueMicrotask(() => dartInstance.exports.$invokeCallback(c)),
      _140: o => o === undefined,
      _142: o => typeof o === 'function' && o[jsWrappedDartFunctionSymbol] === true,
      _146: (l, r) => l === r,
      _147: o => o,
      _148: o => o,
      _149: o => o,
      _150: b => !!b,
      _151: o => o.length,
      _153: (o, i) => o[i],
      _154: f => f.dartFunction,
      _161: (o, p) => o[p],
      _165: o => String(o),
      _166: (p, s, f) => p.then(s, (e) => f(e, e === undefined)),
      _167: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._167(f,arguments.length,x0) }),
      _168: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._168(f,arguments.length,x0,x1) }),
      _169: o => {
        if (o === undefined) return 1;
        var type = typeof o;
        if (type === 'boolean') return 2;
        if (type === 'number') return 3;
        if (type === 'string') return 4;
        if (o instanceof Array) return 5;
        if (ArrayBuffer.isView(o)) {
          if (o instanceof Int8Array) return 6;
          if (o instanceof Uint8Array) return 7;
          if (o instanceof Uint8ClampedArray) return 8;
          if (o instanceof Int16Array) return 9;
          if (o instanceof Uint16Array) return 10;
          if (o instanceof Int32Array) return 11;
          if (o instanceof Uint32Array) return 12;
          if (o instanceof Float32Array) return 13;
          if (o instanceof Float64Array) return 14;
          if (o instanceof DataView) return 15;
        }
        if (o instanceof ArrayBuffer) return 16;
        // Feature check for `SharedArrayBuffer` before doing a type-check.
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
            return 17;
        }
        if (o instanceof Promise) return 18;
        return 19;
      },
      _184: x0 => new ArrayBuffer(x0),
      _205: (x0,x1) => x0.createElement(x1),
      _207: (x0,x1) => x0.querySelector(x1),
      _217: (x0,x1) => x0.replaceChildren(x1),
      _218: x0 => x0.toolVersion,
      _219: x0 => x0.gitInfo,
      _239: o => o instanceof Uint8Array,
      _240: (o, start, length) => new Uint8Array(o.buffer, o.byteOffset + start, length),
      _241: o => o instanceof Int8Array,
      _242: (o, start, length) => new Int8Array(o.buffer, o.byteOffset + start, length),
      _243: o => o instanceof Uint8ClampedArray,
      _244: (o, start, length) => new Uint8ClampedArray(o.buffer, o.byteOffset + start, length),
      _245: o => o instanceof Uint16Array,
      _246: (o, start, length) => new Uint16Array(o.buffer, o.byteOffset + start, length),
      _247: o => o instanceof Int16Array,
      _248: (o, start, length) => new Int16Array(o.buffer, o.byteOffset + start, length),
      _249: o => o instanceof Uint32Array,
      _250: (o, start, length) => new Uint32Array(o.buffer, o.byteOffset + start, length),
      _251: o => o instanceof Int32Array,
      _252: (o, start, length) => new Int32Array(o.buffer, o.byteOffset + start, length),
      _255: o => o instanceof Float32Array,
      _256: (o, start, length) => new Float32Array(o.buffer, o.byteOffset + start, length),
      _257: o => o instanceof Float64Array,
      _258: (o, start, length) => new Float64Array(o.buffer, o.byteOffset + start, length),
      _259: (t, s) => t.set(s),
      _261: (o) => new DataView(o.buffer, o.byteOffset, o.byteLength),
      _263: o => o.buffer,
      _264: o => o.byteOffset,
      _265: Function.prototype.call.bind(Object.getOwnPropertyDescriptor(DataView.prototype, 'byteLength').get),
      _266: (b, o) => new DataView(b, o),
      _267: (b, o, l) => new DataView(b, o, l),
      _268: Function.prototype.call.bind(DataView.prototype.getUint8),
      _269: Function.prototype.call.bind(DataView.prototype.setUint8),
      _270: Function.prototype.call.bind(DataView.prototype.getInt8),
      _271: Function.prototype.call.bind(DataView.prototype.setInt8),
      _272: Function.prototype.call.bind(DataView.prototype.getUint16),
      _273: Function.prototype.call.bind(DataView.prototype.setUint16),
      _274: Function.prototype.call.bind(DataView.prototype.getInt16),
      _275: Function.prototype.call.bind(DataView.prototype.setInt16),
      _276: Function.prototype.call.bind(DataView.prototype.getUint32),
      _277: Function.prototype.call.bind(DataView.prototype.setUint32),
      _278: Function.prototype.call.bind(DataView.prototype.getInt32),
      _279: Function.prototype.call.bind(DataView.prototype.setInt32),
      _284: Function.prototype.call.bind(DataView.prototype.getFloat32),
      _285: Function.prototype.call.bind(DataView.prototype.setFloat32),
      _286: Function.prototype.call.bind(DataView.prototype.getFloat64),
      _287: Function.prototype.call.bind(DataView.prototype.setFloat64),
      _288: Function.prototype.call.bind(Number.prototype.toString),
      _289: Function.prototype.call.bind(BigInt.prototype.toString),
      _290: Function.prototype.call.bind(Number.prototype.toString),
      _803: (x0,x1) => { x0.text = x1 },
      _817: (x0,x1) => { x0.href = x1 },
      _2139: () => globalThis.window,
      _2145: (x0,x1) => x0[x1],
      _4817: (x0,x1) => { x0.textContent = x1 },
      _4821: () => globalThis.document,

    };

    const baseImports = {
      dart2wasm: dart2wasm,
      Math: Math,
      Date: Date,
      Object: Object,
      Array: Array,
      Reflect: Reflect,
      "": new Proxy({}, { get(_, prop) { return prop; } }),

    };

    const jsStringPolyfill = {
      "charCodeAt": (s, i) => s.charCodeAt(i),
      "compare": (s1, s2) => {
        if (s1 < s2) return -1;
        if (s1 > s2) return 1;
        return 0;
      },
      "concat": (s1, s2) => s1 + s2,
      "equals": (s1, s2) => s1 === s2,
      "fromCharCode": (i) => String.fromCharCode(i),
      "length": (s) => s.length,
      "substring": (s, a, b) => s.substring(a, b),
      "fromCharCodeArray": (a, start, end) => {
        if (end <= start) return '';

        const read = dartInstance.exports.$wasmI16ArrayGet;
        let result = '';
        let index = start;
        const chunkLength = Math.min(end - index, 500);
        let array = new Array(chunkLength);
        while (index < end) {
          const newChunkLength = Math.min(end - index, 500);
          for (let i = 0; i < newChunkLength; i++) {
            array[i] = read(a, index++);
          }
          if (newChunkLength < chunkLength) {
            array = array.slice(0, newChunkLength);
          }
          result += String.fromCharCode(...array);
        }
        return result;
      },
      "intoCharCodeArray": (s, a, start) => {
        if (s === '') return 0;

        const write = dartInstance.exports.$wasmI16ArraySet;
        for (var i = 0; i < s.length; ++i) {
          write(a, start++, s.charCodeAt(i));
        }
        return s.length;
      },
      "test": (s) => typeof s == "string",
    };


    

    dartInstance = await WebAssembly.instantiate(this.module, {
      ...baseImports,
      ...additionalImports,
      
      "wasm:js-string": jsStringPolyfill,
      "$moduleHelpers": {"this": () => dartInstance},
    });

    return new InstantiatedApp(this, dartInstance);
  }
}

class InstantiatedApp {
  constructor(compiledApp, instantiatedModule) {
    this.compiledApp = compiledApp;
    this.instantiatedModule = instantiatedModule;
  }

  // Call the main function with the given arguments.
  invokeMain(...args) {
    this.instantiatedModule.exports.$invokeMain(args);
  }
}
